### ISSUE TITLE
How to serve this online

### ISSUE THREAD

**Issue by thodorisgo** [samuraitruong/chess.com-daily-puzzle#1]
Hello,
i managed to install and run localy this repo but i cannot make it work online.
Is there an easy way to achieve this?
Regards

**Comment by samuraitruong** [comment]
Hello, I already deployed this on my github page. you can use it anytime right?
________________________________
From: thodorisgo ***@***.***>
Sent: Saturday, 3 February 2024 8:23 AM
To: samuraitruong/chess.com-daily-puzzle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [samuraitruong/chess.com-daily-puzzle] How to serve this online (Issue #1)


Hello,
i managed to install and run localy this repo but i cannot make it work online.
Is there an easy way to achieve this?
Regards

**Comment by samuraitruong** [comment]
Visit here - https://samuraitruong.github.io/chess.com-daily-puzzle/

**Comment by samuraitruong** [comment]
if you want to host it somewhere, again it only react website, you just need to  build and host as static website
